//! The NDJSON wire protocol spoken over the local socket between the
//! unprivileged GUI and the privileged engine.
//!
//! One JSON object per line, `\n` terminated, in both directions.

use serde::{Deserialize, Serialize};

/// A named connection preset. The uppercase JSON keys are the historical
/// config.json names and are part of the on-disk format.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct Profile {
    pub id: String,
    pub name: String,
    #[serde(rename = "LISTEN_HOST")]
    pub listen_host: String,
    #[serde(rename = "LISTEN_PORT")]
    pub listen_port: u16,
    #[serde(rename = "CONNECT_IP")]
    pub connect_ip: String,
    #[serde(rename = "CONNECT_PORT")]
    pub connect_port: u16,
    #[serde(rename = "FAKE_SNI")]
    pub fake_sni: String,
}

/// Everything the privileged half needs to run a tunnel.
///
/// `config` is the **finished** sing-box configuration, generated by the
/// unprivileged GUI. The engine writes it and runs it; it never parses or
/// rewrites it. The three fields beside it are the only values the engine
/// reads for itself, because routes and firewall rules cannot be expressed
/// inside a sing-box config.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct TunnelSpec {
    pub config: serde_json::Value,
    /// Where the core lives. The engine verifies its SHA-256 against
    /// `corepin::binary_sha256` before executing it — this path arrives
    /// from an unprivileged process and points into a user-writable
    /// directory, so trusting it would hand any local user a root shell.
    pub core_path: String,
    /// How to tell the core is up. Stated explicitly rather than read out
    /// of `config`, so the engine still never parses the configuration.
    pub ready_probe: ReadyProbe,
    /// The SNI upstream. Excluded from the tunnel, and the one destination
    /// the kill switch permits.
    pub connect_ip: String,
    pub connect_port: u16,
    /// The SNI listener's bind address, so a non-loopback one can be
    /// excluded too.
    pub listen_host: String,
}

/// Readiness is probed, never matched against a log line: a core upgrade
/// that rewords "started" would silently break detection.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(tag = "probe", rename_all = "snake_case")]
pub enum ReadyProbe {
    /// Connect to this address until it accepts. Used by the proxy modes.
    TcpAccept { host: String, port: u16 },
    /// Wait for this network interface to exist. Used by TUN mode.
    Interface { name: String },
}

#[derive(Serialize, Deserialize, Clone, Debug)]
#[serde(tag = "cmd", rename_all = "snake_case")]
pub enum Command {
    /// Stop whatever is running, then start this profile.
    Start { profile: Profile },
    Stop,
    /// Turn per-packet logging on or off.
    Verbose { on: bool },
    /// Stop and exit the process.
    Shutdown,
    /// Stop any running tunnel, then start this one. Refused unless the
    /// SNI stage is running.
    TunnelStart { spec: TunnelSpec },
    TunnelStop,
    /// The active SNI profile changed: move the excluded route, update the
    /// permitted destination, and restart the core underneath.
    TunnelReconcile { link: Profile },
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum LogLevel {
    Info,
    Warn,
    Error,
    Debug,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
#[serde(tag = "ev", rename_all = "snake_case")]
pub enum Event {
    /// First line the engine sends after the auth token.
    Ready { version: String },
    /// One of: stopped | starting | running | error
    State { state: String },
    Log { level: LogLevel, msg: String },
    /// A machine-readable failure. `code` is stable; `msg` is for humans.
    Error { code: String, msg: String },
    /// One of: offline | starting | active | holding | fault.
    /// `detail` is a human-readable reason, shown under the condition word.
    TunnelState {
        state: String,
        detail: Option<String>,
    },
    /// Cumulative bytes since this run started, once a second.
    ///
    /// Cumulative rather than deltas on purpose: a dropped or coalesced
    /// line cannot corrupt the total, and the receiver derives the rate
    /// from two samples and the wall clock. A delta stream loses bytes
    /// permanently the first time a line does not arrive.
    Traffic { up: u64, down: u64 },
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn spec() -> TunnelSpec {
        TunnelSpec {
            config: json!({ "log": { "level": "warn" } }),
            core_path: "/home/u/.config/snifake/cores/sing-box-1.13.21/sing-box".into(),
            ready_probe: ReadyProbe::TcpAccept {
                host: "127.0.0.1".into(),
                port: 2080,
            },
            connect_ip: "103.160.204.34".into(),
            connect_port: 443,
            listen_host: "127.0.0.1".into(),
        }
    }

    #[test]
    fn a_tunnel_start_round_trips_through_one_ndjson_line() {
        let line = serde_json::to_string(&Command::TunnelStart { spec: spec() }).unwrap();
        assert!(!line.contains('\n'), "a command must be one line");
        assert!(line.contains("\"cmd\":\"tunnel_start\""), "{line}");
        match serde_json::from_str::<Command>(&line).unwrap() {
            Command::TunnelStart { spec } => {
                assert_eq!(spec.connect_ip, "103.160.204.34");
                assert_eq!(spec.config["log"]["level"], json!("warn"));
                assert_eq!(
                    spec.ready_probe,
                    ReadyProbe::TcpAccept { host: "127.0.0.1".into(), port: 2080 }
                );
            }
            other => panic!("wrong variant: {other:?}"),
        }
    }

    #[test]
    fn tunnel_stop_and_reconcile_carry_their_tags() {
        assert!(serde_json::to_string(&Command::TunnelStop)
            .unwrap()
            .contains("\"cmd\":\"tunnel_stop\""));
        let link = Profile {
            id: "p1".into(),
            name: "n".into(),
            listen_host: "127.0.0.1".into(),
            listen_port: 40443,
            connect_ip: "1.2.3.4".into(),
            connect_port: 443,
            fake_sni: "x.com".into(),
        };
        let line = serde_json::to_string(&Command::TunnelReconcile { link }).unwrap();
        assert!(line.contains("\"cmd\":\"tunnel_reconcile\""), "{line}");
    }

    #[test]
    fn a_tunnel_state_event_round_trips_with_and_without_a_detail() {
        for detail in [None, Some("waiting for LINK".to_string())] {
            let ev = Event::TunnelState {
                state: "holding".into(),
                detail: detail.clone(),
            };
            let line = serde_json::to_string(&ev).unwrap();
            assert!(line.contains("\"ev\":\"tunnel_state\""), "{line}");
            match serde_json::from_str::<Event>(&line).unwrap() {
                Event::TunnelState { state, detail: got } => {
                    assert_eq!(state, "holding");
                    assert_eq!(got, detail);
                }
                other => panic!("wrong variant: {other:?}"),
            }
        }
    }

    #[test]
    fn the_existing_commands_are_untouched() {
        // An older engine must still understand a newer GUI's Stop, and a
        // newer engine an older GUI's — the tags are the contract.
        assert!(serde_json::to_string(&Command::Stop).unwrap().contains("\"cmd\":\"stop\""));
        assert!(serde_json::to_string(&Command::Shutdown)
            .unwrap()
            .contains("\"cmd\":\"shutdown\""));
    }

    #[test]
    fn a_traffic_event_round_trips_and_carries_cumulative_totals() {
        let ev = Event::Traffic { up: 1_048_576, down: 9_437_184 };
        let line = serde_json::to_string(&ev).unwrap();
        assert!(!line.contains('\n'), "an event must be one line");
        assert!(line.contains("\"ev\":\"traffic\""), "{line}");
        match serde_json::from_str::<Event>(&line).unwrap() {
            Event::Traffic { up, down } => {
                assert_eq!(up, 1_048_576);
                assert_eq!(down, 9_437_184);
            }
            other => panic!("wrong variant: {other:?}"),
        }
    }
}
